### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by TanyaKo** [TanyaKo/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ko-tan1** [comment]
<h2>Queen Elizabeth II</h2>
<p>The Queen has ruled for longer than any other Monarch in British history, becoming a much loved and respected figure across the globe. Her extraordinary reign has seen her travel more widely than any other monarch, undertaking many historic overseas visits. Known for her sense of duty and her devotion to a life of service, she has been an important figurehead for the UK and the Commonwealth during times of enormous social change.</p>
