### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by TanyaKo** [TanyaKo/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by ko-tan1** [comment]
<ul class= "contacts">
<li>
<a href= "https://www.royal.uk/her-majesty-the-queen">Her majesty the Queen
</a>
</li>
<li>
<a href= "https://www.britannica.com/biography/Elizabeth-II"> Elizabeth II
</a>
</li>
<li>
<a href= "https://www.bbc.co.uk/teach/queen-elizabeth-ii-britains-longest-reigning/zkfhd6f">Queen Elizabeth II britains longest reigning
</a>
</li>
</ul>

**Comment by TanyaKo** [comment]
Thnx
