### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by TanyaKo** [TanyaKo/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ko-tan1** [comment]
<h3> 15 interesting facts about the Queen </h3>
<ol type = "1">
<li>
Queen Elizabeth II was born at 2.40am on 21 April 1926.
To parents the Duke and Duchess of York, who later became King George VI and Queen Elizabeth (the Queen Mother).
</li>
<li>She was crowned Queen on 2 June 1953.
Watched by a TV audience of 20 million people.
</li>
<li>
She is the longest reigning monarch ever in Britain.
Beating even Queen Victoria (her great-great-grandma!).
</li>
<li>As Queen, she has been served by 14 UK Prime Ministers.
Including Winston Churchill, Margaret Thatcher and more recently, Boris Johnson.
</li>
<li>Her favorite dogs are corgis.
She even invented a new breed of dog when her corgi mated with a dachshund belonging to her sister, Princess Margaret, creating the “dorgi”.
</li>
<li>She’s the only person in the UK allowed to drive without a license.
And she still drives to this day!
</li>
<li>The Queen has two birthdays.
Her actual birthday – 21 April – and her official birthday, which is held on a Saturday in June – when the weather’s better!
</li>
<li>The Queen’s birthplace is now a fancy Cantonese restaurant
Called Hakkasan, at 17 Bruton Street in Mayfair – we hope she likes a takeaway!
</li>
<li>The Queen first sent an email in 1976
… and published her first Instagram post in 2019!
</li>
<li>She has many hobbies
Including horse riding, pigeon racing, and football – she’s an Arsenal supporter!
</li>
<li>Queen Elizabeth became a homeowner at just six years old
When the people of Wales gifted her a house in the grounds of Windsor’s Royal Lodge. Named Y Bwthyn Bach, it means “little cottage”.
</li>
<li> The Queen has sent around 50,000 Christmas cards – and counting!
</li>
<li> She owns an elephant, two giant turtles, a jaguar and a pair of sloths.
Presents from other countries, all of which live in London Zoo.
</li>
<li>Princess Elizabeth made her first radio broadcast in October 1940, during the Second World War.
</li>
<li> Even the monarch can go undercover sometimes.
On a recent low-key trip to Scotland, she met some American tourists while walking. When the tourists asked if she lived locally, she mentioned that she had a house nearby, and when asked if she’d ever met the Queen she simply pointed at her security and said, “No, but he has!”
</li>
</ol>
